spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
      password:
      username:
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-handlers-package: org.example.typehandler
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl